services:
  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=mpharma
      - POSTGRES_PASSWORD=verySecurePASSWORD
      - POSTGRES_DB=icdcodes
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/var/lib/redis/data

  app:
    image: melvinkimathi/mpharma
    container_name: mpharma
    environment:
      - DATABASE_USER=mpharma
      - DATABASE_PASSWORD=verySecurePASSWORD
      - DATABASE_NAME=mpharma
      - DATABASE_HOST=postgresdb
      - DATABASE_PORT=5432
    tty: true
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
      - postgresdb
      - redis