# Generated by Django 4.2.2 on 2023-06-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("code", models.CharField(max_length=12)),
                (
                    "diagnosis_type",
                    models.CharField(
                        choices=[
                            ("CHAPTER", "A chapter in ICD-10"),
                            ("BLOCK", "A block of codes in ICD-10"),
                            ("CATEGORY", "An individual code in ICD-10"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "icd_revision",
                    models.CharField(
                        choices=[
                            ("9", "WHO ICD-9 Standard"),
                            ("10", "WHO ICD-10 Standard"),
                            ("11", "WHO ICD-11 Standard"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
