# Generated by Django 4.2.2 on 2023-06-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("icd_codes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diagnosis",
            name="code",
        ),
        migrations.RemoveField(
            model_name="diagnosis",
            name="description",
        ),
        migrations.RemoveField(
            model_name="diagnosis",
            name="diagnosis_type",
        ),
        migrations.RemoveField(
            model_name="diagnosis",
            name="name",
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="block",
            field=models.CharField(default="0", max_length=12),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="category",
            field=models.CharField(default="A00", max_length=12),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="longDescription",
            field=models.TextField(default="long description sample"),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="shortDescription",
            field=models.TextField(default="short description sample"),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="subcategory",
            field=models.CharField(default="A000", max_length=12),
        ),
    ]
